language: generic 
sudo: required 
services:
  - docker

before_install:
  - docker build -t akashkmr1000/docker-react -f Dockerfile.dev .
   
script:
  - docker run -e CI=true akashkmr1000/docker-react npm run test -- --coverage 
  