sudo: required 
language: generic 

services:
  - docker

before_install:
  - docker build -t akashkmr1000/docker-react -f Dockerfile.dev .
   
script:
  - docker run -p 80:3000 -it akashkmr1000/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "dockerreact-env"
  bucket_name: 'elasticbeanstalk-us-east-2-101577818067'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY